#!/bin/bash

# Firebase Credentials Regeneration Guide
# This error means your Firebase service account key is invalid/expired

echo "================================================================"
echo "🔑 FIREBASE CREDENTIALS ARE INVALID/EXPIRED"
echo "================================================================"
echo ""
echo "The 'Invalid JWT Signature' error means your Firebase service"
echo "account credentials need to be regenerated."
echo ""
echo "================================================================"
echo "📋 STEP-BY-STEP: Generate New Firebase Credentials"
echo "================================================================"
echo ""
echo "1️⃣  Go to Firebase Console:"
echo "   👉 https://console.firebase.google.com/project/parivar-50ef1/settings/serviceaccounts/adminsdk"
echo ""
echo "2️⃣  Click 'Generate New Private Key'"
echo ""
echo "3️⃣  Download the JSON file (it will be named something like:"
echo "   'parivar-50ef1-firebase-adminsdk-xxxxx.json')"
echo ""
echo "4️⃣  Save it as 'firebase_credentials.json' in this directory:"
echo "   $(pwd)"
echo ""
echo "5️⃣  Run this command to encode it for deployment:"
echo "   python3 encode_firebase_creds.py"
echo ""
echo "6️⃣  Update FIREBASE_CREDENTIALS in Render with the new value"
echo ""
echo "================================================================"
echo "⚠️  IMPORTANT NOTES"
echo "================================================================"
echo ""
echo "- Old keys are immediately revoked when you generate new ones"
echo "- Keep the JSON file secure (never commit to Git)"
echo "- After generating, update all deployed instances"
echo ""
echo "================================================================"
echo ""
read -p "Press Enter to open Firebase Console..."

open "https://console.firebase.google.com/project/parivar-50ef1/settings/serviceaccounts/adminsdk"

echo ""
echo "After downloading the new credentials file:"
echo "1. Save it as: firebase_credentials.json"
echo "2. Run: python3 encode_firebase_creds.py"
echo "3. Update Render environment variables"
echo "4. Redeploy"
echo ""

