services:
  - type: web
    name: tg-fets-bot
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: X_BEARER_TOKEN
        sync: false
      - key: X_API_KEY
        sync: false
      - key: X_API_SECRET
        sync: false
      - key: X_ACCESS_TOKEN
        sync: false
      - key: X_ACCESS_TOKEN_SECRET
        sync: false
      - key: ETH_RPC_URL
        sync: false
      - key: BSC_RPC_URL
        sync: false
      - key: BSC_TEST_RPC_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DEMO_MODE
        value: false

